# Generated by Django 4.2.5 on 2023-10-10 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_label', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=50)),
                ('joint', models.BooleanField(default=False)),
                ('financial_institution', models.CharField(max_length=50)),
                ('base_currency', models.CharField(max_length=3)),
                ('date_opened', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('fixed', models.BooleanField(default=True)),
                ('discretionary', models.BooleanField(default=True)),
                ('currency', models.CharField(max_length=3)),
                ('amount_per_frequency', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(max_length=20)),
                ('frequency_detail', models.CharField(blank=True, max_length=200)),
                ('payment_method', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('cancellation_url', models.URLField(blank=True)),
                ('company_logo_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=250)),
                ('payee', models.CharField(blank=True, max_length=50)),
                ('payor', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('type', models.CharField(max_length=20)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('isRecurring', models.BooleanField(default=False)),
                ('account_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='account_relation', to='api.account')),
                ('subscription_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='subscription_transaction', to='api.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('date_paid', models.DateField()),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_history', to='api.subscription')),
            ],
        ),
    ]
