# Generated by Django 4.2.5 on 2023-09-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('fixed', models.BooleanField(default=True)),
                ('discretionary', models.BooleanField(default=True)),
                ('currency', models.CharField(max_length=3)),
                ('amount_per_frequency', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(max_length=20)),
                ('frequency_detail', models.CharField(max_length=200)),
                ('payment_method', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
            ],
        ),
    ]
