# Generated by Django 4.2.5 on 2023-09-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancellation_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='frequency_detail',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
