# Generated by Django 4.2.5 on 2023-10-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_subscription_cancellation_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='company_logo_url',
            field=models.URLField(blank=True),
        ),
    ]
