# Generated by Django 4.2.5 on 2023-10-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_security_secprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='secprice',
            name='date',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
