# Generated by Django 4.2.5 on 2023-11-04 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_secprice_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('owner', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('offset_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('date', models.DateField()),
                ('date_opened', models.DateField()),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('asset_type', models.CharField(max_length=50)),
                ('asset_class', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='secprice',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='api.security'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
